services:
  anupama-frontend:
    image: anupam-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MODE: production
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_WORDPRESS_BASE_URL: ${NEXT_PUBLIC_WORDPRESS_BASE_URL}
        NEXT_PUBLIC_GOOGLE_ANALYTICS: ${NEXT_PUBLIC_GOOGLE_ANALYTICS}
        NEXT_PUBLIC_CLARITY_PROJECT_ID: ${NEXT_PUBLIC_CLARITY_PROJECT_ID}
    env_file:
      - ./.env
    ports:
      - 3000:3000
